### PR TITLE
Add NLP final

### PR DESCRIPTION
**Pull request by ChrisChinchilla**
@amuramoto This is clean now

### CODE REVIEW

**Comment by amuramoto** [comment]
@ChrisChinchilla - Some issues with your PR:

- app.js imports crypto but it is not used. Also not present in package.json
- app.js imports https but it is not used.
- app.js ln 140 implement unneeded isEcho check
- app.js ln 152-165 implements different if block than what is in the tutorial
- app.js ln 173 has an unfinished todo
- app,js implements a postback check and handler, but this shouldn't be needed for an NLP demo AFAIK
- app.js ln 253 Seems unnecessary. Can we just set port number in app.listen instead of the separate app.set('port')?

**Comment by ChrisChinchilla** [comment]
@amuramoto OK, updates pushed and:

* 👍 
* 👍 
* Yeah, I think you changed that in the tutorial and I never noticed that change.
* This was more meant to show the reader they should add to that, but that it was out of scope.
* 👍 
* OK, I think this comes from when I was using the new quick-start to generate my skeleton code instead of the `tutorial-starters` branch. Removed.

Also applied to the start branch for this tutorial.

**Comment by amuramoto** [comment]
Thanks @ChrisChinchilla!

**Comment by rubycalling** [comment]
Pull Request is too old (2018) - This will need to be re-assess.

**Pull request closed without merging**
