### PR TITLE
Ghaethliii

### PR DESCRIPTION
**Pull request by Ghaethliii**
https://github.com/googleads/googleads-mobile-android-mediation/blob/f23b1a236d4b59d84d5f747f4cb09d15ae648f79/CONTRIBUTING.md

### CODE REVIEW

**Comment by Ghaethliii** [comment]
> CONTRIBUTING.md



> CONTRIBUTING.md

**Comment by Ghaethliii** [comment]
https://github.com/fbsamples/messenger-platform-samples/pull/156#issuecomment-995703772

**Comment by Ghaethliii** [comment]
https://github.com/fbsamples/messenger-platform-samples/pull/156#issuecomment-995703772

**Comment by Ghaethliii** [comment]
- [ ]

**Comment by Ghaethliii** [comment]
- [ ] ghaethliii

**Comment by Ghaethliii** [comment]
main

**Review by Ghaethliii — COMMENTED** [review]
- [ ] main
- [ ] 
``
- [ ]

**Comment by Ghaethliii** [comment]
- [ ] .gitignore

**Comment by Ghaethliii** [comment]
.gitignore

**Comment by Ghaethliii** [comment]
gh pr checkout 156

**Comment by Ghaethliii** [comment]
``

**Comment by Ghaethliii** [comment]
https://github.com/googleads/googleads-mobile-android-mediation/blob/f23b1a236d4b59d84d5f747f4cb09d15ae648f79/CONTRIBUTING.md

**Comment by Ghaethliii** [comment]
Duplicate of #

**Comment by Ghaethliii** [comment]
> https://github.com/googleads/googleads-mobile-android-mediation/blob/f23b1a236d4b59d84d5f747f4cb09d15ae648f79/CONTRIBUTING.md

تم

**Comment by Barbog** [comment]
Sorry [Ghaethliii](https://github.com/Ghaethliii), your comments are not informing what you want to do with this pull request. 
Closing.

**Pull request closed without merging**
