### PR TITLE
Add welcome bot final code

### PR DESCRIPTION
**Pull request by ChrisChinchilla**
I think this finally looks clean @amuramoto

### CODE REVIEW

**Comment by amuramoto** [comment]
@ChrisChinchilla - Some issues with your PR:

- app.js crypto and https are imported but not used.
- app.js you require app secret, but doesn't appear to be used anywhere
- app.js ln 285 not sure why you're exporting app?
- appl.js ln 142-153 isEcho and quick reply checks are implemented but doesn't look like the demo uses these.

**Comment by ChrisChinchilla** [comment]
@amuramoto Updated…

* 👍 
* Again, this comes from having used the quick start generator, not using that anymore. I just assumed it was needed for a request, but you're right, apart from a check for it's existence, it's not really needed. Unfortunately, I think this means that all the other code examples also use it for no real purpose, so should we remove from everything, or leave it in to make people aware that it's a possible value?
* Again, from the generator, as with the other PRs, I'll refactor to use the simpler method.
* 👍 

Will also apply to `starter` branch.

**Comment by amuramoto** [comment]
@ChrisChinchilla Re: app secret, if the tutorial does not use it, remove it.

**Comment by jorgeluiso** [comment]
This was never merged, I wonder if it is still relevant. In the mean time closing this PR

**Pull request closed without merging**
