### PR TITLE
Built in nlp start

### PR DESCRIPTION
**Pull request by ChrisChinchilla**
@amuramoto 

And NLP start

### CODE REVIEW

**Comment by amuramoto** [comment]
@ChrisChinchilla  Why are you requiring app secret? I don't see it used anywhere

**Comment by ChrisChinchilla** [comment]
@amuramoto This was built from the quick start so I assumed it was needed in all applications?

**Comment by amuramoto** [comment]
@ChrisChinchilla Nope, only time app secret is required is to decrypt the signed request from getContext

**Comment by ChrisChinchilla** [comment]
@amuramoto Removed from both branches

**Pull request closed without merging**
