### PR TITLE
Adding sample code for the new set of Messenger API blog posts

### PR DESCRIPTION
**Pull request by dmitryvinn-fb**

### CODE REVIEW

**Review by ivannggnnavi — COMMENTED** [review]
Cv

**Review by josh1729 — APPROVED** [review]
@7d2bb6fc5a09dc25a175a93339084a529748a884

**Comment by Thorsmercy** [comment]
7d2bb6fc5a09dc25a175a93339084a529748a884

**Review by Shreyanshbajpai — COMMENTED** [review]
.

**Pull request merged**
